configs:
  Pendulum-v1:
    seed: [0, 1, 2, 3, 4]
    project_name: jaxrl
    exp_name: ddpg
    env_name: Pendulum-v1
    norm_obs: false
    total_timesteps: 300000
    features: [128, 64]
    lr_critic: 0.001
    lr_actor: 0.0005
    gamma: 0.99
    tau: 0.001
    target_update_interval: 1
    exploration_type: normal_noise
    exploration_noise: 0.1
    exploration_noise_end: 0.0
    exploration_noise_decay: true
    ou_theta: 0.15
    epsilon_start: 1.0
    epsilon_end: 0.05
    exploration_fraction: 0.5
    num_env: 1
    update_interval: 4
    train_batch_size: 64
    buffer_size: 1000000
    learning_start: 10000
    eval_interval: 8192
    eval_num_steps: 2000
    eval_num_env: 16
    log_interval: 8192
    wandb: true
    ckpt_path: /home/zhixin/jaxrl-learning/ckpts/
    silent: false
    save_model: true
    run_name: null
    vmap_run: true

  MountainCarContinuous-v0:
    seed: [0, 1, 2, 3, 4]
    project_name: jaxrl
    exp_name: ddpg
    env_name: MountainCarContinuous-v0
    norm_obs: false
    total_timesteps: 300000
    features: [128, 64]
    lr_critic: 0.001
    lr_actor: 0.001
    gamma: 0.99
    tau: 0.001
    target_update_interval: 1
    exploration_type: ou_noise
    exploration_noise: 0.8
    exploration_noise_end: 0.0
    exploration_noise_decay: false
    ou_theta: 0.15
    # ou_theta: 0.
    epsilon_start: 1.0
    epsilon_end: 0.05
    exploration_fraction: 0.9
    num_env: 1
    update_interval: 4
    train_batch_size: 64
    buffer_size: 100000
    learning_start: 10000
    eval_interval: 8192
    eval_num_steps: 2000
    eval_num_env: 16
    log_interval: 8192
    wandb: true
    ckpt_path: /home/zhixin/jaxrl-learning/ckpts/
    silent: false
    save_model: true
    run_name: null
    vmap_run: true

  Ant-brax:
    seed: 0
    exp_name: ddpg
    project_name: jaxrl
    env_name: Ant-brax
    norm_obs: true
    total_timesteps: 50000000
    features: [256, 256]
    lr_critic: 0.0003
    lr_actor: 0.0003
    gamma: 0.99
    tau: 0.001
    target_update_interval: 1
    exploration_type: normal_noise
    exploration_noise: 0.2
    exploration_noise_end: 0.0
    exploration_noise_decay: false
    ou_theta: 0.15
    epsilon_start: 1.0
    epsilon_end: 0.05
    exploration_fraction: 0.9
    num_env: 1024
    update_interval: 256
    train_batch_size: 1024
    buffer_size: 1000000
    learning_start: 100000
    eval_interval: 4194304
    eval_num_steps: 2000
    eval_num_env: 16
    log_interval: 4194304
    wandb: true
    save_model: true
    run_name: null
    ckpt_path: /home/zhixin/jaxrl-learning/ckpts/
    silent: false
    vmap_run: false
