configs:
  MountainCar-v0:
    project_name: jaxrl
    exp_name: dqn
    env_name: MountainCar-v0
    seed: [0, 1, 2, 3, 4]
    total_timesteps: 200000
    lr: 0.00025
    gamma: 0.99
    tau: 0.005
    target_update_freq: 1
    epsilon_start: 1.0
    epsilon_end: 0.05
    exploration_fraction: 0.5
    num_env: 1
    train_interval: 4
    train_batch_size: 128
    buffer_size: 10000
    learning_start: 10000
    eval_interval: 8192
    eval_num_steps: 500
    eval_num_env: 16
    log_interval: 8192
    features: [128, 64]
    wandb: false
    save_model: true
    ckpt_path: /home/zhixin/jaxrl-learning/ckpts/
    vmap_run: false
    silent: false

  CartPole-v1:
    project_name: jaxrl
    exp_name: dqn
    env_name: CartPole-v1
    seed: [0, 1, 2, 3, 4]
    total_timesteps: 200000
    lr: 0.00025
    gamma: 0.99
    tau: 0.005
    target_update_freq: 1
    epsilon_start: 1.0
    epsilon_end: 0.05
    exploration_fraction: 0.5
    num_env: 1
    train_interval: 4
    train_batch_size: 128
    buffer_size: 10000
    learning_start: 10000
    eval_interval: 8192
    eval_num_steps: 500
    eval_num_env: 16
    log_interval: 8192
    features: [128, 64]
    wandb: false
    save_model: true
    ckpt_path: /home/zhixin/jaxrl-learning/ckpts/
    vmap_run: false
    silent: false

  Acrobot-v1:
    project_name: jaxrl
    exp_name: dqn
    env_name: Acrobot-v1
    seed: [0, 1, 2, 3, 4]
    total_timesteps: 200000
    lr: 0.00025
    gamma: 0.99
    tau: 0.005
    target_update_freq: 1
    epsilon_start: 1.0
    epsilon_end: 0.05
    exploration_fraction: 0.5
    num_env: 1
    train_interval: 4
    train_batch_size: 128
    buffer_size: 10000
    learning_start: 10000
    eval_interval: 8192
    eval_num_steps: 500
    eval_num_env: 16
    log_interval: 8192
    features: [128, 64]
    wandb: false
    save_model: true
    ckpt_path: /home/zhixin/jaxrl-learning/ckpts/
    vmap_run: false
    silent: false
